window.ONESHOT_CONFIG = {
    statsUrl: "/api/stats",
    inventoryUrl: "/api/inventory",
    movementsUrl: "/api/movements",
    searchUrl: "/api/search",
    cameraStatusUrl: "/camera_status",
    videoFeedUrl: "/video_feed",
    modeUrl: "/api/mode",
    triggerStatusUrl: "/api/trigger_status",
    dbStatusUrl: "/db_status",
    embeddingUrl: "/api/objects/embedding",
    faceStatusUrl: "/api/face/status",
    faceModeUrl: "/api/face/mode",
    faceRegisterUrl: "/api/face/register",
    faceClearUrl: "/api/face/clear",
    facePollMs: 220,
    mediapipeVisionUrl: "/vendor/mediapipe/vision_bundle.mjs",
    mediapipeWasmUrl: "/vendor/mediapipe/wasm",
    mediapipeFaceModelUrl: "/vendor/mediapipe/models/face_landmarker.task",

    searchDebounceMs: 150,
    cameraPollMs: 2000,
    cameraRetryMs: 1500,
    statsAnimMs: 1000,
    triggerPollMs: 500,
    dbRetryMs: 5000
};
