const E={file:document.querySelector('#file'),name:document.querySelector('#name'),mask:document.querySelector('#mask'),save:document.querySelector('#save'),undo:document.querySelector('#undo'),size:document.querySelector('#size'),msg:document.querySelector('#message'),image:document.querySelector('#image'),maskLayer:document.querySelector('#maskLayer'),points:document.querySelector('#pointsLayer'),preview:document.querySelector('#preview')};
const S={id:null,prompts:[],tool:'points',drawing:false,undo:null,saved:false};const I=E.image.getContext('2d'),M=E.maskLayer.getContext('2d',{willReadFrequently:true}),P=E.points.getContext('2d'),V=E.preview.getContext('2d');
function say(t,bad=false){E.msg.textContent=t;E.msg.style.color=bad?'#ff9aaa':'#9db1c0'}
async function post(url,data){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.detail||'Request failed');return j}
function resize(w,h){[E.image,E.maskLayer,E.points,E.preview].forEach(c=>{c.width=w;c.height=h})}
function at(e){const r=E.points.getBoundingClientRect();return{x:Math.max(0,Math.min(E.points.width-1,(e.clientX-r.left)*E.points.width/r.width)),y:Math.max(0,Math.min(E.points.height-1,(e.clientY-r.top)*E.points.height/r.height))}}
function redraw(){P.clearRect(0,0,E.points.width,E.points.height);S.prompts.forEach(p=>{P.beginPath();P.arc(p.x,p.y,7,0,Math.PI*2);P.fillStyle=p.label?'#5ee9a0':'#ff6b88';P.fill();P.strokeStyle='white';P.stroke()});E.mask.disabled=!S.prompts.length}
function hasMask(){let d=M.getImageData(0,0,E.maskLayer.width,E.maskLayer.height).data;for(let i=3;i<d.length;i+=4)if(d[i])return true;return false}
function preview(){V.fillStyle='white';V.fillRect(0,0,E.preview.width,E.preview.height);if(hasMask()){let t=document.createElement('canvas');t.width=E.image.width;t.height=E.image.height;let c=t.getContext('2d');c.drawImage(E.image,0,0);let a=document.createElement('canvas');a.width=t.width;a.height=t.height;let ac=a.getContext('2d'),src=M.getImageData(0,0,a.width,a.height),out=ac.createImageData(a.width,a.height);for(let i=0;i<src.data.length;i+=4)out.data[i+3]=src.data[i+3]?255:0;ac.putImageData(out,0,0);c.globalCompositeOperation='destination-in';c.drawImage(a,0,0);V.drawImage(t,0,0)}E.save.disabled=!hasMask()||S.saved}
function snapshot(){S.undo=M.getImageData(0,0,E.maskLayer.width,E.maskLayer.height)}
function stroke(p){M.save();M.globalCompositeOperation=S.tool==='erase'?'destination-out':'source-over';M.fillStyle='rgba(0,212,200,.5)';M.beginPath();M.arc(p.x,p.y,+E.size.value/2,0,Math.PI*2);M.fill();M.restore()}
E.file.onchange=()=>{let f=E.file.files[0];if(!f)return;let r=new FileReader();r.onload=async()=>{try{say('Uploading image…');let x=await post('/api/image',{filename:f.name,image_data:r.result}),im=new Image();im.onload=()=>{resize(x.width,x.height);I.drawImage(im,0,0);M.clearRect(0,0,x.width,x.height);S.id=x.session_id;S.prompts=[];S.undo=null;S.saved=false;redraw();preview();say('Image ready. Add point prompts.');};im.src=r.result}catch(e){say(e.message,true)}};r.readAsDataURL(f)};
E.points.oncontextmenu=e=>e.preventDefault();E.points.onpointerdown=e=>{if(!S.id)return;let p=at(e);if(S.tool==='points'){S.prompts.push({...p,label:e.button===2?0:1});redraw()}else{S.drawing=true;snapshot();E.points.setPointerCapture(e.pointerId);stroke(p);preview()}};E.points.onpointermove=e=>{if(S.drawing){stroke(at(e));preview()}};E.points.onpointerup=()=>S.drawing=false;
document.querySelectorAll('button[id=points],button[id=brush],button[id=erase]').forEach(b=>b.onclick=()=>{S.tool=b.id==='points'?'points':b.id==='brush'?'brush':'erase';document.querySelectorAll('#points,#brush,#erase').forEach(x=>x.classList.toggle('active',x.id===b.id))});
E.undo.onclick=()=>{if(S.undo){let now=M.getImageData(0,0,E.maskLayer.width,E.maskLayer.height);M.putImageData(S.undo,0,0);S.undo=now;preview()}};
E.mask.onclick=async()=>{try{say('SAM is generating a mask…');let d=await post('/api/mask',{session_id:S.id,points:S.prompts.map(p=>[p.x,p.y]),labels:S.prompts.map(p=>p.label)}),im=new Image();im.onload=()=>{snapshot();M.clearRect(0,0,E.maskLayer.width,E.maskLayer.height);M.drawImage(im,0,0);M.globalCompositeOperation='source-in';M.fillStyle='rgba(0,212,200,.5)';M.fillRect(0,0,E.maskLayer.width,E.maskLayer.height);M.globalCompositeOperation='source-over';S.tool='brush';document.querySelector('#brush').click();preview();say('Mask ready. Refine with brush or eraser.')};im.src=d.mask_data}catch(e){say(e.message,true)}};
function maskData(){let src=M.getImageData(0,0,E.maskLayer.width,E.maskLayer.height),c=document.createElement('canvas');c.width=E.maskLayer.width;c.height=E.maskLayer.height;let ctx=c.getContext('2d'),out=ctx.createImageData(c.width,c.height);for(let i=0;i<src.data.length;i+=4){let v=src.data[i+3]?255:0;out.data[i]=out.data[i+1]=out.data[i+2]=v;out.data[i+3]=255}ctx.putImageData(out,0,0);return c.toDataURL('image/png')}
E.save.onclick=async()=>{if(!E.name.value.trim())return say('Enter an object name first.',true);try{E.save.disabled=true;say('Creating OpenCLIP embedding and inserting into pgvector…');let d=await post('/api/register',{session_id:S.id,object_name:E.name.value.trim(),mask_data:maskData()});S.saved=true;say(`Registered successfully. Database row ID: ${d.id}`)}catch(e){E.save.disabled=false;say(e.message,true)}};
