artifact_location: file:///c:/Users/Haqkiem/OneDrive/UNIKL/July-2026/Competition/AIIC/PETROSAINS/train_v2/runs/mlflow/432051828201252182
creation_time: 1789194168515
experiment_id: '432051828201252182'
last_update_time: 1789194168515
lifecycle_stage: active
name: C:\Users\Haqkiem\OneDrive\UNIKL\July-2026\Competition\AIIC\PETROSAINS\train_v2\runs
